Models/ErrorViewModel.cs
namespace CRUD_Motor.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MotorInfo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CRUD_Motor.Models
{
    [Table("motor_info")]
    public class MotorInfo
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }

        [Required]
        [Column("brand")]
        [StringLength(50, ErrorMessage = "Brand can not be longer than 50 characters")]
        public string Brand { get; set; }

        [Required]
        [Column("model")]
        [StringLength(50, ErrorMessage = "Model can not be longer than 50 characters")]
        public string Model { get; set; }

        [Required]
        [Column("displacement")]
        [Range(0.1, 10.0, ErrorMessage = "Displacement must be between 0.1 and 10.0 liters")]
        public float Displacement { get; set; }

        [Required]
        [Column("cylinders")]
        [Range(1, 16, ErrorMessage = "Cylinders must be between 1 and 16")]
        public int Cylinders { get; set; }

        [Required]
        [Column("aspiration")]
        [StringLength(20, ErrorMessage = "Aspiration can not be longer than 20 characters")]
        public string Aspiration { get; set; }

        [Required]
        [Column("horse_power")]
        [Range(0, 2000, ErrorMessage = "HorsePower must be between 0 and 2000")]
        public int HorsePower { get; set; }

        [Required]
        [Column("torque")]
        [Range(0, 2000, ErrorMessage = "Torque must be between 0 and 2000")]
        public int Torque { get; set; }

        [Required]
        [Column("fuel_type")]
        [EnumDataType(typeof(FuelTypeEnum))]
        public FuelTypeEnum FuelType { get; set; }

        [NotMapped]
        public string FuelTypeName => FuelType.ToString();

        [Required]
        [Column("is_turbocharged")]
        public bool IsTurbocharged { get; set; }

        [Required]
        [Column("year")]
        [Range(1886, 2100, ErrorMessage = "Year must be between 1886 and 2100")]
        public int Year { get; set; }
    }

        public enum FuelTypeEnum
    {
        Gasoline = 1,
        Diesel = 2,
        Electric = 3
    }
    
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CRUD_Motor.Models;

namespace CRUD_Motor.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MotorInfoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CRUD_Motor.Data;
using CRUD_Motor.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.VisualBasic.FileIO;

namespace CRUD_Motor.Controllers
{
    [Route("[controller]")]
    public class MotorInfoController : Controller
    {
        private readonly ILogger<MotorInfoController> _logger;
        private readonly ApplicationDBContext _context;

        public MotorInfoController(ILogger<MotorInfoController> logger, ApplicationDBContext Context)
        {
            _logger = logger;
            _context = Context;
        }

        [Route("[action]")]


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        public async Task<IActionResult> Index()
        {
            var motorInfos = await _context.MotorInfos.ToListAsync();
            return View(motorInfos);
        }

        // GET: MotorInfo/Create
        [Route("create")]
        public IActionResult Create()
        {

            return View();
        }

        // POST: MotorInfo/Create
        [HttpPost("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MotorInfo motorInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(motorInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                _logger.LogError("Error creating new motor");
                return View(motorInfo);
            }
        }

        [Route("edit/{id}")]

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var motorInfo = await _context.MotorInfos.FindAsync(id);
            if (motorInfo == null)
            {
                return NotFound();
            }
            return View(motorInfo);
        }

        [HttpPost("edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Brand,Model,Displacement,Cylinders,Aspiration,HorsePower,Torque,FuelType,isTurbocharged,Year")] MotorInfo motorInfo)
        {
            if (id != motorInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(motorInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MotorInfoExists(motorInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(motorInfo);
            }
        }

        [Route("delete/{id}")]

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var motorInfo = await _context.MotorInfos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (motorInfo == null)
            {
                return NotFound();
            }

            return View(motorInfo);
        }

        [HttpPost("delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var motorInfo = await _context.MotorInfos.FindAsync(id);
            _context.MotorInfos.Remove(motorInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //details
        [Route("details/{id}")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var motorInfo = await _context.MotorInfos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (motorInfo == null)
            {
                return NotFound();
            }

            return View(motorInfo);
        }
        

        private bool MotorInfoExists(Guid id)
        {
            return _context.MotorInfos.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/MotorInfo/Create.cshtml
@model CRUD_Motor.Models.MotorInfo

@{
    ViewData["Title"] = "Create Motor Info";
}

<h2>Create Motor</h2>

<form asp-action="Create" class="form gap-2">
    <div class="form-group">
        <label asp-for="Brand" class="control-label"></label>
        <input asp-for="Brand" class="form-control" />
        <span asp-validation-for="Brand" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Model" class="control-label"></label>
        <input asp-for="Model" class="form-control" />
        <span asp-validation-for="Model" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Displacement" class="control-label"></label>
        <input asp-for="Displacement" class="form-control" type="number" step="0.1" />
        <span asp-validation-for="Displacement" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Cylinders" class="control-label"></label>
        <input asp-for="Cylinders" class="form-control" type="number" />
        <span asp-validation-for="Cylinders" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Aspiration" class="control-label"></label>
        <input asp-for="Aspiration" class="form-control" />
        <span asp-validation-for="Aspiration" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="HorsePower" class="control-label"></label>
        <input asp-for="HorsePower" class="form-control" type="number" />
        <span asp-validation-for="HorsePower" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Torque" class="control-label"></label>
        <input asp-for="Torque" class="form-control" type="number" />
        <span asp-validation-for="Torque" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="FuelType" class="control-label"></label>
        <select asp-for="FuelType" class="form-control" asp-items="Html.GetEnumSelectList<CRUD_Motor.Models.FuelTypeEnum>()">
        </select>
        <span asp-validation-for="FuelType" class="text-danger"></span>
    </div>

    <div class="form-group form-check mt-2">
    <input asp-for="IsTurbocharged" class="form-check-input" type="checkbox" />
    <label asp-for="IsTurbocharged" class="form-check-label">turbocharged</label>
</div>


    <div class="form-group">
        <label asp-for="Year" class="control-label"></label>
        <input asp-for="Year" class="form-control" type="number" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>

    <div class="form-group mt-3">
        <input type="submit" value="Create" class="btn btn-success" />
    </div>
</form>


<p class="mt-3">
    <a asp-controller="MotorInfo" asp-action="Index" class="btn btn-primary">Back to List</a>
</p>

Views/MotorInfo/Delete.cshtml
@model CRUD_Motor.Models.MotorInfo;

@{
    ViewData["Title"] = "Delete Motor";
}

<h2>Delete Motor</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MotorInfo</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Brand
        </dt>
        <dd class="col-sm-10">
            @Model.Brand
        </dd>
        <dt class="col-sm-2">
            Model
        </dt>  
        <dd class="col-sm-10">
            @Model.Model
        </dd>
        <dt class="col-sm-2">
            Fuel Type
        </dt>
        <dd class="col-sm-10">
            @Model.FuelType
        </dd>
        <dt class="col-sm-2">
            Year
        </dt>
        <dd class="col-sm-10">
            @Model.Year
        </dd>
    </dl>
</div>

<form asp-action="Delete" asp-route-id="@Model.Id" method="post">
    <input type="submit" value="Delete" class="btn btn-danger" />
    <a asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

Views/MotorInfo/Details.cshtml
@model CRUD_Motor.Models.MotorInfo

@{
    ViewData["Title"] = "Details";
}

<h2>Motor Details</h2>

<div>
    <h4>Motor Information</h4>
    <hr />

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Displacement)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Displacement)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cylinders)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cylinders)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Aspiration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Aspiration)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HorsePower)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HorsePower)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Torque)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Torque)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FuelType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FuelTypeName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsTurbocharged)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsTurbocharged)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
    </dl>

    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

Views/MotorInfo/Edit.cshtml
@model CRUD_Motor.Models.MotorInfo

@{
    ViewData["Title"] = "Edit Motor Info";
}

<h2>Edit Motor</h2>
<form asp-controller="MotorInfo" asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="Brand" class="control-label"></label>
        <input asp-for="Brand" class="form-control" />
        <span asp-validation-for="Brand" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Model" class="control-label"></label>
        <input asp-for="Model" class="form-control" />
        <span asp-validation-for="Model" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Displacement" class="control-label"></label>
        <input asp-for="Displacement" class="form-control" type="number" step="0.1" />
        <span asp-validation-for="Displacement" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Cylinders" class="control-label"></label>
        <input asp-for="Cylinders" class="form-control" type="number" />
        <span asp-validation-for="Cylinders" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Aspiration" class="control-label"></label>
        <input asp-for="Aspiration" class="form-control" />
        <span asp-asp-validation-for="Aspiration" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="HorsePower" class="control-label"></label>
        <input asp-for="HorsePower" class="form-control" type="number" />
        <span asp-validation-for="HorsePower" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Torque" class="control-label"></label>
        <input asp-for="Torque" class="form-control" type="number" />
        <span asp-validation-for="Torque" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="FuelType" class="control-label"></label>
        <select asp-for="FuelType" class="form-control" asp-items="Html.GetEnumSelectList<CRUD_Motor.Models.FuelTypeEnum>()">
        </select>
        <span asp-validation-for="FuelType" class="text-danger"></span>
    </div>

    <div class="form-group form-check mt-2">
    <input asp-for="IsTurbocharged" class="form-check-input" type="checkbox" />
    <label asp-for="IsTurbocharged" class="form-check-label">turbocharged</label>
    <span asp-validation-for="IsTurbocharged" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Year" class="control-label"></label>
        <input asp-for="Year" class="form-control" type="number" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-success" />
    </div>
</form>

<p class="mt-3">
    <a asp-controller="MotorInfo" asp-action="Index" class="btn btn-primary">Back to List</a>
</p>

Views/MotorInfo/Index.cshtml
@model IEnumerable<CRUD_Motor.Models.MotorInfo>

@{
    ViewBag.Title = "Index";
}
<div class="text-center">
    <h1 class="display-4">this is the INDEX view</h1>
</div>

<p>
    <a asp-controller="MotorInfo" asp-action="Create" class="btn btn-primary">Create a new motor</a>
</p>

<table class="table text-center table-striped">
    <thead>
        <tr>
            <th>Brand</th>
            <th>Model</th>
            <th>Fuel Type</th>
            <th>Year</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Brand</td>
            <td>@item.Model</td>
            <td>@item.FuelTypeName</td>
            <td>@item.Year</td>
            <td><a asp-controller="MotorInfo" asp-action="Details" class="btn btn-info" asp-route-id="@item.Id">Details</a> 
            | <a asp-controller="MotorInfo" asp-action="Edit" class="btn btn-success" asp-route-id="@item.Id">Edit</a> 
            | <a asp-controller="MotorInfo" asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a></td>
        </tr>
    }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_Motor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_Motor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD_Motor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MotorInfo" asp-action="Index">Motorgasolina</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUD_Motor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>